### ISSUE TITLE
Mouse movement must be used for navigation not mouse movement *and* hold button

### ISSUE THREAD

**Issue by farooqkz** [P1X-in/tanks-of-freedom-ii#14]
Hello. I don't know what is the right thing, but in most games like this, especially Battle of Wesnoth, we can move mouse to navigate *without* having to hold the mouse button. It is also the case for many strategy but not turn based games I've tried such as warzone2100 and 0ad.

**Comment by czlowiekimadlo** [comment]
I have made it be similar to ToF1, where this was required to operate on touch screens, but since this game is not targeting mobile devices, I was already thinking about redoing these controls to be more in-line with other PC games.

**Comment by czlowiekimadlo** [comment]
I have extended the options for moving the camera. What can be used now:
- Hold left mouse button and move
- Hold right mouse button and move (not in Editor)
- Move mouse cursor to the edge of the screen (togglable in game Settings)

These changes will be available in version 0.6.0.
