### ISSUE TITLE
A single keystroke for ending the turn

### ISSUE THREAD

**Issue by farooqkz** [P1X-in/tanks-of-freedom-ii#15]
I think a single light keystroke(without having to hold it down for seconds) is more user friendly for ending turns. Also there must be a warning and confirmation when a player tries to end their turn when they've made no move at all.

**Comment by czlowiekimadlo** [comment]
I have added a setting where player can configure the end turn delay to be up to x4 faster. There is also a prompt to confirm if player did not spend any AP during their turn.
