### ISSUE TITLE
Link in the "about" section is scam

### ISSUE THREAD

**Issue by FabulousOne** [P1X-in/tanks-of-freedom-ii#18]
Hi, 
just a little note: the link `http://tof.p1x.in/` in the about text of this Github project is leading to a spam site. 
Please delete it. Thanks.

**Comment by czlowiekimadlo** [comment]
Thanks for the heads up. This site is hosted and managed by @w84death and right now it looks down, I can no longer see the website, just some generic nginx page. I assume his server might have been compromised and he is on it.
