### ISSUE TITLE
Stuck on opponent turn in Noble Intentions - Research and development

### ISSUE THREAD

**Issue by Huitsi** [P1X-in/tanks-of-freedom-ii#21]
I ran into a game-halting issue in the Research and development mission of the Noble Intentions campaign.
The enemy turn after my turn 12 gets stuck and never ends.

Steps to reproduce:

1. Load [save0.tofsave.json](https://github.com/P1X-in/tanks-of-freedom-ii/files/15168248/save0.tofsave.json)
2. End turn
3. Watch the enemy play, eventually zooming in on the bridge (or thereabouts)
4. Wait forever as nothing happens

I'm playing with cloned source code.

**Comment by czlowiekimadlo** [comment]
Thank you for your report! That saved game was very useful for reporoduction. The bug has been found and squashed, fix will be available in the next version of the game (or just build from source :)

**Comment by czlowiekimadlo** [comment]
Fixed in c51416020c3fc3906368baab5a4925faba9db559
